job_extraction_task:
  description: >
    {location}에서 {level} 레벨 {position} 직무를 찾아 추출합니다.

    Steps include:
    1. 웹 검색 도구를 사용하여 {location}에서 {level} 레벨 {position} 직무를 검색합니다.
    2. 검색 결과에서 구인 공고를 추출합니다.
    3. {location}에서 {level} 레벨 {position} 직무가 아닌 직무를 필터링합니다.
  expected_output: >
    `JobList` schema와 일치하는 JSON 객체입니다.
  agent: job_search_agent

job_matching_task:
  description: >
    귀하는 커리어 매칭 전문가입니다.

    추출된 직무 목록(JobList)과 사용자 이력서가 주어졌을 때, 각 직무가 사용자의 다음 사항과 얼마나 잘 부합하는지 평가합니다.
    - 기술 스택
    - 역할 수준
    - 산업 및 회사 규모 선호도
    - 원격/근무 유연성
    - 계약 유형
    - 급여 기대치
    - 이력서의 키워드 및 결격 사유

    각 직무에 대해 1(적합하지 않음)에서 5(적합함)까지의 `match_score`를 할당하고 그 이유를 설명합니다.

    목록의 각 직무에 `match_score`와 `reason` 필드를 추가합니다.

    모든 원래 직무 필드는 그대로 유지합니다. 직무를 변경하거나 필터링하지 않습니다.
  expected_output: >
    원래 `JobList` 스키마와 일치하는 JSON 객체(직무당 두 개 추가 필드 포함):
    - match_score: 1부터 5까지의 정수
    - reason: 점수에 대한 간략한 설명
  agent: job_matching_agent

job_selection_task:
  description: >
    귀하는 직무 선택 전문가입니다.

    각각 `match_score`와 `reason` 필드가 포함된 채용 공고 목록(RankedJobList)이 주어졌을 때, 다음과 같은 작업을 수행해야 합니다.
    1. `match_score`와 이유를 분석하여 사용자에게 **가장 적합한 채용 공고**를 결정합니다.
    2. 사용자의 선호도, 기술 및 목표에 가장 부합하는 단일 최적의 채용 공고를 선택합니다.
    3. 이력서-채용 공고의 연관성을 고려하여 간결한 `reason` 필드로 선택 이유를 설명합니다.
    4. 최상위 채용 공고의 `selected` 필드를 `true`로 설정하고, 나머지 모든 채용 공고의 `false` 필드를 설정합니다.

    원래 채용 공고 필드(예: job_title, company_name 등)의 내용은 변경하지 마세요.
  expected_output: >
    선택한 채용 공고의 `ChosenJob` 스키마와 일치하는 JSON 객체입니다.
  agent: job_matching_agent

resume_rewriting_task:
  description: >
    귀하는 이력서 최적화 전문가입니다.

    사용자의 실제 이력서(포함된 지식 소스로 제공됨)와 선택된 직무(ChosenJob)를 고려하여, 
    **기존 이력서를 재작성**하여 **직무와의 연관성을 강조**하되, **사실을 조작하거나 부풀리지 않아야 합니다**.

    중점 사항:
    - 관련 기술, 프로젝트 및 업적을 재정렬, 재구성 및 강조
    - 주요 직무 요구 사항 및 키워드를 반영하도록 요약 및 경력 요점을 재작성
    - 채용 공고의 어조, 기술 중심 및 용어와 일치
    - 사용자의 원본 이력서에서 실제 경력만 유지

    명확성을 위해 관련 없는 내용을 삭제하거나 제목을 약간 수정할 수 있지만, **가짜 회사, 기술, 날짜 또는 직책을 추가해서는 안 됩니다**.

  expected_output: >
    **실제 사용자 이력서**를 마크다운 형식으로 재작성하여 선택된 직무에 맞게 최적화합니다.
    이력서는 진실성을 유지해야 하며 사용자의 실제 경력에 기반해야 합니다.

  agent: resume_optimization_agent
  output_file: output/rewritten_resume.md
  create_directory: true
  markdown: true

company_research_task:
  description: >
    귀하는 회사 조사 및 면접 준비 전문가입니다.

    선택한 직무(ChosenJob)를 고려하여 공개 웹 리소스를 활용하여 채용 기업을 조사하십시오.
    목표는 다음과 같습니다.
    1. 회사의 규모, 산업, 사명, 가치 및 최신 뉴스를 파악합니다.
    2. 채용 공고를 분석하여 팀 구조와 제품 맥락을 추론합니다.
    3. 지원자가 직면할 수 있는 잠재적인 면접 주제와 질문을 제시합니다.
    4. 면접 중 지원자가 질문할 수 있는 통찰력 있는 질문 목록을 제공합니다.

    회사 웹사이트, 보도자료, 블로그, 소셜 미디어 및 리뷰를 활용하여 통찰력을 수집합니다.
  expected_output: >
    다음 섹션이 포함된 마크다운 파일:
    - ## 회사 개요
    - ## 사명 및 가치
    - ## 최근 소식 또는 변경 사항
    - ## 역할 맥락 및 제품 참여
    - ## 예상 인터뷰 주제
    - ## 추천 질문

  agent: company_research_agent
  markdown: true
  output_file: output/company_research.md

interview_prep_task:
  description: >
    면접 준비 코치입니다.

    다음 정보를 종합하세요.
    1. 채용 공고(ChosenJob)
    2. 맞춤형 이력서(RewrittenResume)
    3. 회사 조사 요약(CompanyResearch)

    다음을 포함하는 상세한 면접 준비 문서를 작성하세요.
    - 직무에 대한 간략한 요약 및 지원자에게 적합한 이유
    - 가장 관련성 있는 부분에 초점을 맞춘 맞춤형 이력서 요약
    - 회사, 제품 및 가치에 대한 간결한 요약
    - 직무 및 회사에 따른 예상 면접 질문
    - 지원자가 면접관에게 질문할 수 있는 맞춤형 질문
    - 어조, 집중 영역 및 주의해야 할 위험 신호에 대한 조언

    문서는 깔끔하고 명확해야 하며, 면접에서 지원자에게 전략적 우위를 제공하도록 설계되어야 합니다.

    문서는 너무 짧지 않아야 하며, 필요한 만큼 시간을 들여 포괄적으로 작성해야 합니다.
  expected_output: >
   "면접 준비: $CompanyName – $JobTitle"이라는 제목의 마크다운 문서이며, 다음 섹션으로 구성됩니다.
    - ## 직무 개요
    - ## 이 직무가 적합한 이유
    - ## 이 직무에 대한 이력서 주요 내용
    - ## 회사 요약
    - ## 예상 면접 질문
    - ## 면접관에게 질문할 수 있는 질문
    - ## 알아야 할/검토해야 할 개념
    - ## 전략적 조언
  agent: interview_prep_agent
  output_file: output/interview_prep.md